version: '3'

services:
  server-shark:
    container_name: server-shark
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - network-shark

networks:
  network-shark:
    driver: bridge
  