# NOTE, THIS IS NOT A GOOD WAY OF KEEPING SECRET. THIS FILE SHOULD BE HIDDEN. (ADDITIONALY, NOT THE SAFEST PASSWORD MEASURES ARE IN PLACE).

PASSWORD_SALT = 'b5NhTxB6LOuvrhDOaoEe'

JWT_SECRET = 'QPVgKnspjoHWXjU3KNor'